#!/usr/bin/env bash

BASE="$HOME"/code/experiments

DATE="$(date --iso-8601=date)"

EXP_DIR="$BASE"/"$DATE"_"$1"

mkdir -p $EXP_DIR

echo "cd $EXP_DIR"

echo "python -m venv .venv; . .venv/bin/activate; pip install ipykernel pandas pyarrow;"
